In [3]:
#1. Read mobile dataset using pandas, and preprocess it (fill null values).
import pandas as pd
dd=pd.read_csv("mobile_cleaned.csv")
dd.isnull()

sim_type  aperture  gpu_rank  weight  stand_by_time  processor_frequency  \
0       False     False     False   False          False                False   
1       False     False     False   False          False                False   
2       False     False     False   False          False                False   
3       False     False     False   False          False                False   
4       False     False     False   False          False                False   
..        ...       ...       ...     ...            ...                  ...   
104     False     False     False   False          False                False   
105     False     False     False   False          False                False   
106     False     False     False   False          False                False   
107     False     False     False   False          False                False   
108     False     False     False   False          False                False   

     thickness  flash_type  front_camera_resolution  auto_focus  ...  \
0        False       False                    False       False  ...   
1        False       False                    False       False  ...   
2        False       False                    False       False  ...   
3        False       False                    False       False  ...   
4        False       False                    False       False  ...   
..         ...         ...                      ...         ...  ...   
104      False       False                    False       False  ...   
105      False       False                    False       False  ...   
106      False       False                    False       False  ...   
107      False       False                    False       False  ...   
108      False       False                    False       False  ...   

     micro_sd_slot  screen_pixel_density  water_proof_rate  phone_width  \
0            False                 False             False        False   
1            False                 False             False        False   
2            False                 False             False        False   
3            False                 False             False        False   
4            False                 False             False        False   
..             ...                   ...               ...          ...   
104          False                 False             False        False   
105          False                 False             False        False   
106          False                 False             False        False   
107          False                 False             False        False   
108          False                 False             False        False   

     expandable_memory  version  usb_type  battery_capacity  processor_rank  \
0                False    False     False             False           False   
1                False    False     False             False           False   
2                False    False     False             False           False   
3                False    False     False             False           False   
4                False    False     False             False           False   
..                 ...      ...       ...               ...             ...   
104              False    False     False             False           False   
105              False    False     False             False           False   
106              False    False     False             False           False   
107              False    False     False             False           False   
108              False    False     False             False           False   

     is_liked  
0       False  
1       False  
2       False  
3       False  
4       False  
..        ...  
104     False  
105     False  
106     False  
107     False  
108     False  

[109 rows x 40 columns]

In [6]:
import numpy as np
p=[[1,0],[0,1]]
q=[[1,2],[3,4]]
c=np.outer(p,q)

print(c)

[[1 2 3 4]
 [0 0 0 0]
 [0 0 0 0]
 [1 2 3 4]]


In [6]:
#5. write a NumPy program to compute the sum of the diagonal element of a given array(matrix).
import numpy as np
m=np.arange(9).reshape(3,3)
print("original matrix:")
print(m)
r=np.trace(m)
print("sum of diagonal element:",r)

original matrix:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
sum of diagonal element: 12


In [11]:
4.#Write a numpy program to compute the condition number of a given matrix.
import numpy as np
s=np.array([[5,6],[3,4]])
print("matrix:")
print(s)
c=np.linalg.cond(s)
print("The condition number of a given matrix:",c)

matrix:
[[5 6]
 [3 4]]
The condition number of a given matrix: 42.97673159491458
